src/KupaTourist/Models/DbInitializer.cs
using KupaTourist.DAL.Entities;
using KupaTourist.DAL.Repositories;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace KupaTourist.Models
{
    public static class DbInitializer
        {
            public static void Seed(IApplicationBuilder applicationBuilder)
            {
                AppDbContext context = applicationBuilder.ApplicationServices.GetRequiredService<AppDbContext>();


                if (!context.Rooms.Any())
                {
                    context.AddRange(
                        new Room { Name = "room1", Price = 350, IsBooked = false, Reservations = { new Reservation { ReservationFrom = new DateTime(2018, 2, 16), ReservationTo = new DateTime(2018, 2, 18) } } },
                        new Room { Name = "room2", Price = 450, IsBooked = true, Reservations = { new Reservation { ReservationFrom = new DateTime(2018, 3, 16), ReservationTo = new DateTime(2018, 3, 18) } } },
                        new Room { Name = "room3", Price = 550, IsBooked = false, Reservations = { new Reservation { ReservationFrom = new DateTime(2018, 4, 16), ReservationTo = new DateTime(2018, 4, 18) } } },
                        new Room { Name = "room4", Price = 650, IsBooked = true, Reservations = { new Reservation { ReservationFrom = new DateTime(2018, 5, 16), ReservationTo = new DateTime(2018, 5, 18) } } }

                    );
                }

           

            context.SaveChanges();
            }



        }
    }

src/KupaTourist/ViewModels/HomeViewModel.cs
using KupaTourist.DAL.Entities;
using System.Collections.Generic;

namespace KupaTourist.ViewModels
{
    public class HomeViewModel
    {

        public IEnumerable<Room> RoomIsBooked { get; set; }
    }
}

src/KupaTourist/ViewModels/RoomsListViewModel.cs
using KupaTourist.DAL.Entities;
using System.Collections.Generic;

namespace KupaTourist.ViewModels
{
    public class RoomsListViewModel
    {
        public IEnumerable<Room> Rooms { get; set; }
    }
}

src/KupaTourist/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KupaTourist.Controllers
{
    public class ContactController : Controller
    {
        
        public ViewResult Index()
        {
            return View();
        }
    }
}

src/KupaTourist/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using KupaTourist.DAL.Repositories;
using KupaTourist.ViewModels;


// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KupaTourist.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRoomRepository _roomRepository;

        public HomeController(IRoomRepository roomRepository)
        {
            _roomRepository = roomRepository;
        }

        public ViewResult Index()
        {
            var model = new HomeViewModel
            {
                RoomIsBooked = _roomRepository.AvailableRoom
            };
            return View(model);
        }
    }
}

src/KupaTourist/Controllers/RoomController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using KupaTourist.ViewModels;
using KupaTourist.DAL.Repositories;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KupaTourist.Controllers
{
    public class RoomController : Controller
    {
        private IRoomRepository _roomRepository;

        public RoomController(IRoomRepository roomRepository)
        {
            _roomRepository = roomRepository;
        }

        
        public ViewResult List()
        {
            RoomsListViewModel roomsList = new RoomsListViewModel();
            roomsList.Rooms = _roomRepository.Rooms;
            return View(roomsList);
        }

        public ViewResult Details(int id)
        {
            var model = _roomRepository.Rooms.Where(r => r.RoomId == id).FirstOrDefault();
            return View(model);
        }
    }
}

src/KupaTourist/Views/Contact/Index.cshtml
<div class="whiteColorDiv">
    <h1>Contact Kupa Tourist</h1>
    <h4>If you have any questions don't hesitate to get in touch</h4>

    <button type="button" class="btn btn-lg " data-toggle="modal" data-target="#myModal">Contact us</button>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Email address</label>
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">Example textarea</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default" data-dismiss="modal">Send</button>
                </div>
            </div>

        </div>
    </div>
</div>

src/KupaTourist/Views/Home/Index.cshtml
@model HomeViewModel


<div class="row">
   
    <div class="page-header">
        <h1>Available rooms</h1>
    </div>
    @foreach(var room in Model.RoomIsBooked)
    {
        @Html.Partial("RoomIsBookedSummary", room)

    }

</div>

src/KupaTourist/Views/Room/Details.cshtml
@model Room
   <div>
       <h1>DETAILS</h1>
    </div>
<div class="whiteColorDiv">
    <h3 class="pull-right ">@Model.Price.ToString("c")</h3>
    <h3>@Model.Name</h3>
    
    <p>@Model.ShortDescription</p>
    @foreach (var item in Model.Reservations)
    {
        <h4>@item.ReservationFrom</h4>
    }
    
</div>

src/KupaTourist/Views/Room/List.cshtml
@model RoomsListViewModel


@foreach (var room in Model.Rooms)
{

    @Html.Partial("RoomOverViewSummary", room)
    
}

src/KupaTourist/Views/Shared/RoomIsBookedSummary.cshtml
@model Room

<div class="mydiv">
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="http://placehold.it/64x64">
            <div class="caption">
                <h3 class="pull-right">@Model.Price.ToString("c")</h3>
                <h3>
                   @Html.ActionLink(Model.Name, "Details", "Room", new { id = Model.RoomId })
                </h3>
                <p>Available</p>
            </div>
        </div>
    </div>
</div>

src/KupaTourist/Views/Shared/RoomOverViewSummary.cshtml
@model Room

<div class="mydiv">
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="http://placehold.it/64x64">
            <div class="caption">
                <h3 class="pull-right">@Model.Price.ToString("c")</h3>
                <h3>
                    @Html.ActionLink(Model.Name, "Details", new { id = Model.RoomId})
                </h3>
                @if (Model.IsBooked)
                {
                    <p>Already booked</p>

                }
                else
                {
                    <p>Available</p>

                }
                               

            </div>
        </div>
    </div>
</div>

src/KupaTourist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Kupa Tourist</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                    <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rooms <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Room" asp-action="List">All Rooms</a></li>
                            <li><a asp-controller="Home" asp-action="Index">Available Rooms</a></li>
                        
                        </ul>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
        <div class="row">
            <div id="imgDiv" class="col-md-3 ">
                <p class="lead">
                     <img class="img-responsive" src="~/Images/logo.png"  alt="" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>